name: Deploy Google Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Google Apps Script
        uses: Mayu-mic/google-apps-script-action@v1
        with:
          clasprc: ${{ secrets.CLASPRC_JSON }}
          scriptId: ${{ secrets.SCRIPT_ID }}
          command: 'push'